try:
    print(x)
except(NameError):
    print("erro encontrado")